(async () => {
  'use strict';
  const K=window.KaligaGol,el=id=>document.getElementById(id),loginPanel=el('login-panel'),dashboard=el('dashboard'),logoutButton=el('logout-button'),loginForm=el('admin-login'),loginMessage=el('login-message'),teamsList=el('teams-list');
  let settings=null,teams=[],notes=[],audit=[],filtered=[];
  function text(tag,value,className=''){const e=document.createElement(tag);e.textContent=value;if(className)e.className=className;return e;}
  function cleanNumber(v){return K.toEnglishDigits(v).replace(/\D/g,'');}
  function validNationalId(v){const c=cleanNumber(v);if(!/^\d{10}$/.test(c)||/^(\d)\1{9}$/.test(c))return false;const s=c.slice(0,9).split('').reduce((a,d,i)=>a+Number(d)*(10-i),0),r=s%11,x=r<2?r:11-r;return Number(c[9])===x;}
  function validDate(y,m,d){return Number.isInteger(y)&&y>=1300&&y<=1500&&Number.isInteger(m)&&m>=1&&m<=12&&Number.isInteger(d)&&d>=1&&d<=(m<=6?31:30);}
  function oldEnough(y,m,d){const latest=[Number(settings.age_reference_year)-Number(settings.min_age),Number(settings.age_reference_month),Number(settings.age_reference_day)],b=[y,m,d];for(let i=0;i<3;i++){if(b[i]<latest[i])return true;if(b[i]>latest[i])return false;}return true;}
  async function isAdmin(uid){const {data,error}=await K.client.from('gol_admins').select('user_id').eq('user_id',uid).maybeSingle();if(error)throw error;return!!data;}
  function toLocal(iso){const d=new Date(iso),o=d.getTimezoneOffset();return new Date(d.getTime()-o*60000).toISOString().slice(0,16);}
  async function openPrivate(path){const url=await K.signedUrl(path,300);window.open(url,'_blank','noopener');}
  function fileButton(label,path){const b=text('button',path?label:`${label} ـ ثبت نشده`,'mini-link');b.type='button';b.disabled=!path;b.dataset.path=path||'';b.addEventListener('click',()=>b.dataset.path&&openPrivate(b.dataset.path).catch(()=>alert('بازکردن فایل ممکن نشد.')));return b;}
  function input(value,max,mode=''){const i=document.createElement('input');i.value=value??'';i.maxLength=max;if(mode)i.inputMode=mode;return i;}
  function field(label,node){const d=document.createElement('div');d.className='field';d.append(text('label',label),node);return d;}
  async function invokeAction(body){const {data,error}=await K.client.functions.invoke('gol-admin-actions',{body});if(error){let message=error.message||'عملیات سرور انجام نشد.';try{const detail=await error.context.json();message=detail.error||message}catch{}throw new Error(message)}if(!data?.ok)throw new Error(data?.error||'عملیات انجام نشد.');return data;}

  function nextPaint() { return new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve))); }

  async function renderElementToPdfBlob(element) {
    if (typeof window.html2canvas !== 'function') throw new Error('کتابخانه ساخت تصویر گزارش بارگذاری نشده است.');
    const JsPdf = window.jspdf?.jsPDF || window.jsPDF;
    if (!JsPdf) throw new Error('کتابخانه ساخت PDF بارگذاری نشده است.');
    const blocker = document.createElement('div');
    blocker.setAttribute('aria-hidden','true');
    blocker.style.cssText='position:fixed;inset:0;z-index:2147483647;display:flex;align-items:center;justify-content:center;background:#07111f;color:#fff;font-family:Tahoma,Arial,sans-serif;font-size:18px;text-align:center;padding:24px';
    blocker.textContent='در حال ساخت فایل خلاصه ثبت‌نام…';
    document.body.appendChild(blocker);
    try {
      element.style.cssText='position:fixed;left:0;top:0;z-index:2147483646;display:block;visibility:visible;opacity:1;direction:rtl;background:#fff;color:#111;font-family:Tahoma,Arial,sans-serif;width:760px;padding:34px;line-height:1.8;box-sizing:border-box;overflow:visible';
      document.body.appendChild(element);
      if(document.fonts?.ready) await document.fonts.ready;
      await nextPaint(); await new Promise(r=>setTimeout(r,180));
      const width=Math.max(760,element.scrollWidth),height=Math.max(400,element.scrollHeight);
      const canvas=await window.html2canvas(element,{scale:2,useCORS:true,backgroundColor:'#ffffff',logging:false,width,height,windowWidth:Math.max(900,width),windowHeight:Math.max(1200,height)});
      if(!canvas||canvas.width<100||canvas.height<100) throw new Error('تصویر گزارش ساخته نشد.');
      const ctx=canvas.getContext('2d',{willReadFrequently:true}),pixels=ctx.getImageData(0,0,canvas.width,canvas.height).data,step=Math.max(4,Math.floor((canvas.width*canvas.height)/25000));let visible=0;
      for(let p=0;p<pixels.length;p+=4*step){if(pixels[p+3]>20&&(pixels[p]<245||pixels[p+1]<245||pixels[p+2]<245)){visible++;if(visible>80)break;}}
      if(visible<=80) throw new Error('محتوای گزارش سفید تشخیص داده شد.');
      const pdf=new JsPdf({orientation:'portrait',unit:'mm',format:'a4',compress:true});
      const pageWidth=210,pageHeight=297,margin=8,printableWidth=pageWidth-margin*2,printableHeight=pageHeight-margin*2,pagePixelHeight=Math.floor(canvas.width*printableHeight/printableWidth);let y=0,page=0;
      while(y<canvas.height){const h=Math.min(pagePixelHeight,canvas.height-y),pc=document.createElement('canvas');pc.width=canvas.width;pc.height=h;const c=pc.getContext('2d');c.fillStyle='#fff';c.fillRect(0,0,pc.width,pc.height);c.drawImage(canvas,0,y,canvas.width,h,0,0,canvas.width,h);if(page>0)pdf.addPage();pdf.addImage(pc.toDataURL('image/jpeg',.96),'JPEG',margin,margin,printableWidth,h*printableWidth/canvas.width,undefined,'FAST');y+=h;page++;}
      const blob=pdf.output('blob');if(!(blob instanceof Blob)||blob.size<3000)throw new Error('فایل PDF نهایی ساخته نشد.');return blob;
    } finally { blocker.remove(); element.remove(); }
  }

  function buildReport(team){const root=document.createElement('section');const h=text('h1','خلاصه ثبت‌نام مسابقات گل کوچک کالیگا');h.style.cssText='font-size:24px;text-align:center;margin:0 0 20px';root.appendChild(h);const meta=document.createElement('div');meta.style.cssText='border:1px solid #ccc;border-radius:12px;padding:14px;margin-bottom:18px';[['نام تیم',team.team_name],['شماره تماس کاپیتان',team.captain_phone],['هزینه ثبت‌نام',K.formatToman(settings.fee_toman)],['مهلت ثبت‌نام',settings.deadline_label],['آخرین بازسازی',new Date().toLocaleString('fa-IR')]].forEach(([l,v])=>{const p=document.createElement('p'),s=text('strong',`${l}: `);p.style.margin='4px 0';p.append(s,document.createTextNode(v));meta.appendChild(p)});root.appendChild(meta);const table=document.createElement('table');table.style.cssText='width:100%;border-collapse:collapse;font-size:13px';const hr=document.createElement('tr');['ردیف','نقش','نام و نام خانوادگی','نام پدر','شماره ملی','تاریخ تولد'].forEach(v=>{const th=text('th',v);th.style.cssText='border:1px solid #bbb;padding:8px;background:#eee';hr.appendChild(th)});const thead=document.createElement('thead');thead.appendChild(hr);table.appendChild(thead);const tbody=document.createElement('tbody');[...(team.gol_players||[])].sort((a,b)=>a.player_order-b.player_order).forEach(p=>{const tr=document.createElement('tr');[K.toPersianDigits(p.player_order),p.is_captain?'کاپیتان':'بازیکن',p.full_name,p.father_name,K.toPersianDigits(p.national_id),`${K.toPersianDigits(p.birth_year)}/${K.toPersianDigits(String(p.birth_month).padStart(2,'0'))}/${K.toPersianDigits(String(p.birth_day).padStart(2,'0'))}`].forEach(v=>{const td=text('td',v);td.style.cssText='border:1px solid #bbb;padding:8px;text-align:center';tr.appendChild(td)});tbody.appendChild(tr)});table.appendChild(tbody);root.appendChild(table);return root;}
  async function regenerateReport(team){const blob=await renderElementToPdfBlob(buildReport(team)),path=`${team.owner_id}/reports/registration-summary-${Date.now()}.pdf`;const up=await K.client.storage.from(K.config.storageBucket).upload(path,new File([blob],'registration-summary.pdf',{type:'application/pdf'}),{upsert:false,contentType:'application/pdf',cacheControl:'0'});if(up.error)throw up.error;const save=await K.client.rpc('gol_admin_set_report_path',{p_team_id:team.id,p_report_path:path});if(save.error)throw save.error;return path;}
  function eventLabel(a){return({registration_completed:'تکمیل ثبت‌نام',receipt_submitted:'ارسال فیش',admin_status_changed:'تغییر وضعیت توسط مدیر',team_player_updated:'ویرایش بازیکن توسط تیم',admin_player_updated:'ویرایش بازیکن توسط مدیر',report_updated:'بروزرسانی PDF',password_reset:'بازیابی رمز توسط مدیر',team_deleted:'حذف تیم'})[a]||a;}
  function stats(){const all=teams.length,approved=teams.filter(t=>t.status==='approved').length,pending=teams.filter(t=>['awaiting_payment','payment_submitted'].includes(t.status)).length,correction=teams.filter(t=>t.status==='needs_correction').length,incomplete=teams.filter(t=>t.status==='incomplete'||(t.gol_players||[]).length<5).length,paid=teams.filter(t=>!!t.payment_receipt_path).length;const data=[['کل تیم‌ها',all],['تأییدشده',approved],['در انتظار',pending],['نیازمند اصلاح',correction],['ثبت ناقص',incomplete],['فیش‌دار',paid]];const box=el('admin-stats');box.textContent='';data.forEach(([l,v])=>{const c=document.createElement('div');c.className='stat-card';c.append(text('span',l),text('strong',K.toPersianDigits(v)));box.appendChild(c)});el('team-count').textContent=`${K.toPersianDigits(all)} تیم`;}
  function applyFilters(){const q=K.normalizeIdentifier(el('team-search').value),status=el('status-filter').value,pay=el('payment-filter').value,inc=el('incomplete-only').checked;filtered=teams.filter(t=>{const players=t.gol_players||[],hay=[t.team_name,t.captain_phone,...players.flatMap(p=>[p.full_name,p.father_name,p.national_id])].map(K.normalizeIdentifier).join(' '),isInc=t.status==='incomplete'||players.length<5;return(!q||hay.includes(q))&&(!status||t.status===status)&&(!pay||(pay==='paid'?!!t.payment_receipt_path:!t.payment_receipt_path))&&(!inc||isInc)});renderTeams();}
  function noteFor(teamId){return notes.find(n=>n.team_id===teamId)?.note||'';}
  function auditFor(teamId){return audit.filter(a=>a.team_id===teamId).slice(0,20);}
  function makePlayerEditor(team,p){const box=document.createElement('section');box.className='player-editor hidden';box.append(text('h4',`ویرایش ${p.is_captain?'کاپیتان':`بازیکن ${K.toPersianDigits(p.player_order)}`}`));const grid=document.createElement('div');grid.className='form-grid';const full=input(p.full_name,100),father=input(p.father_name,80),nid=input(p.national_id,10,'numeric'),year=input(p.birth_year,4,'numeric'),month=input(p.birth_month,2,'numeric'),day=input(p.birth_day,2,'numeric'),insurance=document.createElement('input');insurance.type='file';insurance.accept='image/jpeg,image/png,application/pdf';grid.append(field('نام و نام خانوادگی',full),field('نام پدر',father),field('کد ملی',nid),field('سال تولد',year),field('ماه',month),field('روز',day),field('بیمه جدید ـ اختیاری',insurance));box.appendChild(grid);const actions=document.createElement('div');actions.className='admin-actions';const save=text('button','ذخیره بازیکن','button primary');save.type='button';const msg=text('span','','message');save.addEventListener('click',async()=>{save.disabled=true;K.setMessage(msg,'در حال ذخیره...','info');try{const f=full.value.trim(),fa=father.value.trim(),n=cleanNumber(nid.value),y=Number(cleanNumber(year.value)),m=Number(cleanNumber(month.value)),d=Number(cleanNumber(day.value));if(f.length<3||fa.length<2||!validNationalId(n)||!validDate(y,m,d)||!oldEnough(y,m,d))throw new Error('اطلاعات بازیکن معتبر نیست.');let path=null,file=insurance.files[0];if(file){const er=K.validateFile(file,6);if(er)throw new Error(er);path=`${team.owner_id}/insurance/player-${p.player_order}-${Date.now()}.${K.safeExtension(file)}`;const up=await K.client.storage.from(K.config.storageBucket).upload(path,file,{upsert:false,contentType:file.type,cacheControl:'0'});if(up.error)throw up.error;}const r=await K.client.rpc('gol_admin_update_player',{p_player_id:p.id,p_full_name:f,p_father_name:fa,p_national_id:n,p_birth_year:y,p_birth_month:m,p_birth_day:d,p_insurance_path:path});if(r.error){if(r.error.code==='23505')throw new Error('این کد ملی قبلاً ثبت شده است.');throw r.error}K.setMessage(msg,'بازیکن ذخیره شد؛ در حال بازسازی PDF...','info');try{await regenerateReport(team);K.setMessage(msg,'بازیکن و PDF بروزرسانی شد.','success')}catch(e){K.setMessage(msg,'بازیکن ذخیره شد، اما PDF بازسازی نشد.','error')}setTimeout(loadAll,700)}catch(e){console.error(e);K.setMessage(msg,e.message||'ذخیره انجام نشد.','error');save.disabled=false}});actions.append(save,msg);box.appendChild(actions);return box;}
  function renderTeams(){teamsList.textContent='';if(!filtered.length){teamsList.appendChild(text('div','تیمی با این فیلتر پیدا نشد.','empty'));return}filtered.forEach(team=>{const card=document.createElement('article');card.className='team-admin-card';const head=document.createElement('div');head.className='team-admin-head';const info=document.createElement('div');info.append(text('h3',team.team_name),text('p',`تماس: ${K.toPersianDigits(team.captain_phone)} • ثبت: ${K.formatDateTime(team.created_at)}`));const meta=document.createElement('div');meta.className='admin-card-meta';meta.append(text('span',`${K.toPersianDigits((team.gol_players||[]).length)} بازیکن`,'tag-small'),text('span',`${K.toPersianDigits(team.replacement_count||0)} از ۲ تعویض`,'tag-small'));if(team.changes_pending_review)meta.append(text('span','تغییرات جدید تیم','tag-small warning'));if(team.status==='incomplete'||(team.gol_players||[]).length<5)meta.append(text('span','ثبت ناقص','tag-small danger'));info.appendChild(meta);head.append(info,text('span',K.statusLabels[team.status]||team.status,`status-badge ${team.status}`));card.appendChild(head);
    const tableWrap=document.createElement('div');tableWrap.className='table-wrap';const table=document.createElement('table');table.className='data-table';const hr=document.createElement('tr');['نقش','نام','نام پدر','کد ملی','تولد','بیمه','ویرایش'].forEach(v=>hr.appendChild(text('th',v)));const thead=document.createElement('thead');thead.appendChild(hr);table.appendChild(thead);const tbody=document.createElement('tbody'),editors=document.createElement('div');[...(team.gol_players||[])].sort((a,b)=>a.player_order-b.player_order).forEach(p=>{const tr=document.createElement('tr');[p.is_captain?'کاپیتان':`بازیکن ${K.toPersianDigits(p.player_order)}`,p.full_name,p.father_name,K.toPersianDigits(p.national_id),`${K.toPersianDigits(p.birth_year)}/${K.toPersianDigits(String(p.birth_month).padStart(2,'0'))}/${K.toPersianDigits(String(p.birth_day).padStart(2,'0'))}`].forEach(v=>tr.appendChild(text('td',v)));const fc=document.createElement('td');fc.appendChild(fileButton('مشاهده',p.insurance_path));tr.appendChild(fc);const ec=document.createElement('td'),edit=text('button','ویرایش','mini-link');edit.type='button';const editor=makePlayerEditor(team,p);edit.addEventListener('click',()=>{editor.classList.toggle('hidden');edit.textContent=editor.classList.contains('hidden')?'ویرایش':'بستن'});ec.appendChild(edit);tr.appendChild(ec);tbody.appendChild(tr);editors.appendChild(editor)});table.appendChild(tbody);tableWrap.appendChild(table);card.append(tableWrap,editors);
    const files=document.createElement('div');files.className='file-links';files.append(fileButton('فیش واریزی',team.payment_receipt_path));const report=fileButton('خلاصه PDF',team.registration_report_path),rebuild=text('button','بازسازی PDF','mini-link'),rf=text('span','','message');rebuild.type='button';rebuild.addEventListener('click',async()=>{rebuild.disabled=true;K.setMessage(rf,'در حال بازسازی...','info');try{const p=await regenerateReport(team);team.registration_report_path=p;report.dataset.path=p;report.disabled=false;K.setMessage(rf,'PDF جدید ساخته شد.','success')}catch(e){K.setMessage(rf,e.message||'بازسازی انجام نشد.','error')}rebuild.disabled=false});files.append(report,rebuild,rf);card.appendChild(files);
    const controls=document.createElement('div');controls.className='form-grid';controls.style.marginTop='14px';const select=document.createElement('select');['incomplete','awaiting_payment','payment_submitted','approved','needs_correction','rejected'].forEach(v=>{const o=document.createElement('option');o.value=v;o.textContent=K.statusLabels[v];o.selected=team.status===v;select.appendChild(o)});const publicNote=document.createElement('textarea');publicNote.value=team.admin_note||'';publicNote.maxLength=800;controls.append(field('وضعیت ثبت‌نام',select),field('پیام قابل مشاهده برای تیم',publicNote));card.appendChild(controls);const statusActions=document.createElement('div');statusActions.className='admin-actions';const saveStatus=text('button','ذخیره وضعیت','button primary'),statusMsg=text('span','','message');saveStatus.type='button';saveStatus.addEventListener('click',async()=>{saveStatus.disabled=true;const r=await K.client.rpc('gol_admin_set_status',{p_team_id:team.id,p_status:select.value,p_note:publicNote.value.trim()||null});if(r.error){K.setMessage(statusMsg,r.error.message||'ذخیره نشد.','error');saveStatus.disabled=false;return}K.setMessage(statusMsg,'وضعیت ذخیره شد.','success');setTimeout(loadAll,500)});statusActions.append(saveStatus,statusMsg);card.appendChild(statusActions);
    const privateBox=document.createElement('section');privateBox.className='private-note-box';privateBox.append(text('strong','یادداشت خصوصی مدیر'));const privateNote=document.createElement('textarea');privateNote.value=noteFor(team.id);privateNote.maxLength=2000;privateNote.placeholder='این متن برای تیم نمایش داده نمی‌شود.';privateNote.style.width='100%';const savePrivate=text('button','ذخیره یادداشت خصوصی','mini-link'),privateMsg=text('span','','message');savePrivate.type='button';savePrivate.addEventListener('click',async()=>{savePrivate.disabled=true;const r=await K.client.rpc('gol_admin_save_private_note',{p_team_id:team.id,p_note:privateNote.value.trim()});if(r.error)K.setMessage(privateMsg,'ذخیره یادداشت انجام نشد.','error');else K.setMessage(privateMsg,'یادداشت خصوصی ذخیره شد.','success');savePrivate.disabled=false});privateBox.append(privateNote,savePrivate,privateMsg);card.appendChild(privateBox);
    const passwordBox=document.createElement('section');passwordBox.className='panel';passwordBox.style.marginTop='12px';passwordBox.append(text('h4','بازیابی رمز تیم'));const pw=input('',72);pw.type='text';pw.placeholder='رمز موقت حداقل ۸ نویسه';const generate=text('button','ساخت رمز','button'),reset=text('button','تعیین رمز جدید','button gold'),pwMsg=text('span','','message');generate.type=reset.type='button';generate.addEventListener('click',()=>{const chars='ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789@#';let v='';crypto.getRandomValues(new Uint32Array(12)).forEach(n=>v+=chars[n%chars.length]);pw.value=v;pw.select()});reset.addEventListener('click',async()=>{if(pw.value.length<8){K.setMessage(pwMsg,'رمز حداقل ۸ نویسه باشد.','error');return}if(!confirm(`رمز ورود تیم «${team.team_name}» تغییر کند؟`))return;reset.disabled=true;K.setMessage(pwMsg,'در حال بازیابی رمز...','info');try{await invokeAction({action:'reset_password',team_id:team.id,new_password:pw.value});K.setMessage(pwMsg,'رمز جدید ثبت شد؛ آن را فقط به کاپیتان تحویل دهید.','success')}catch(e){K.setMessage(pwMsg,e.message,'error')}reset.disabled=false});const tools=document.createElement('div');tools.className='password-tools';tools.append(field('رمز موقت جدید',pw),generate,reset);passwordBox.append(tools,pwMsg);card.appendChild(passwordBox);
    const history=document.createElement('details');history.style.marginTop='12px';const summary=text('summary','تاریخچه تغییرات');history.appendChild(summary);const list=document.createElement('div');list.className='activity-list';auditFor(team.id).forEach(a=>{const d=text('div',eventLabel(a.action),'activity-item'),tm=text('time',K.formatDateTime(a.created_at));d.appendChild(tm);list.appendChild(d)});if(!list.children.length)list.appendChild(text('div','رویدادی ثبت نشده است.','empty'));history.appendChild(list);card.appendChild(history);
    const danger=document.createElement('section');danger.className='danger-zone';danger.append(text('strong','حذف کامل تیم'),text('p','حساب ورود، اطلاعات بازیکنان و فایل‌های این تیم حذف می‌شود و بازگشت‌پذیر نیست.'));const del=text('button','حذف کامل تیم','button danger'),delMsg=text('span','','message');del.type='button';del.addEventListener('click',async()=>{const typed=prompt(`برای حذف، نام تیم را دقیق وارد کنید:\n${team.team_name}`);if(typed!==team.team_name){if(typed!==null)K.setMessage(delMsg,'نام تیم مطابق نبود؛ حذف لغو شد.','error');return}del.disabled=true;K.setMessage(delMsg,'در حال حذف کامل...','info');try{await invokeAction({action:'delete_team',team_id:team.id});K.setMessage(delMsg,'تیم حذف شد.','success');setTimeout(loadAll,700)}catch(e){K.setMessage(delMsg,e.message,'error');del.disabled=false}});danger.append(del,delMsg);card.appendChild(danger);teamsList.appendChild(card)});}
  async function loadSettings(){settings=await K.getSettings();el('registration-open').checked=settings.registration_open;el('deadline-input').value=toLocal(settings.registration_deadline);el('deadline-label').value=settings.deadline_label;el('minimum-age').value=settings.min_age;el('fee-input').value=settings.fee_toman;el('bank-account').value=settings.bank_account||'';el('account-holder').value=settings.account_holder||'';}
  async function loadAll(){teamsList.innerHTML='<div class="empty">در حال دریافت اطلاعات...</div>';const [t,n,a]=await Promise.all([K.client.from('gol_teams').select('*, gol_players(*)').order('created_at',{ascending:false}),K.client.from('gol_admin_team_notes').select('*'),K.client.from('gol_audit_log').select('*').order('created_at',{ascending:false}).limit(2000)]);if(t.error)throw t.error;teams=t.data||[];notes=n.data||[];audit=a.data||[];stats();applyFilters();}
  async function showDashboard(session){if(!await isAdmin(session.user.id)){await K.client.auth.signOut();throw new Error('این حساب دسترسی مدیریت ندارد.')}loginPanel.classList.add('hidden');dashboard.classList.remove('hidden');logoutButton.classList.remove('hidden');await loadSettings();await loadAll();}
  const statusFilter=el('status-filter');Object.entries(K.statusLabels).forEach(([v,l])=>{const o=document.createElement('option');o.value=v;o.textContent=l;statusFilter.appendChild(o)});['team-search','status-filter','payment-filter','incomplete-only'].forEach(id=>el(id).addEventListener(id==='team-search'?'input':'change',applyFilters));
  loginForm.addEventListener('submit',async e=>{e.preventDefault();const b=e.currentTarget.querySelector('button'),u=el('admin-username').value.trim(),p=el('admin-password').value,store='kaliga-admin-login-guard-v1';let g={fails:0,blockedUntil:0};try{g=JSON.parse(localStorage.getItem(store)||JSON.stringify(g))}catch{}if(g.blockedUntil>Date.now()){K.setMessage(loginMessage,'ورود مدیر موقتاً محدود شده است.','error');return}b.disabled=true;K.setMessage(loginMessage,'در حال ورود...','info');try{const email=await K.accountEmail('admin',u),{data,error}=await K.client.auth.signInWithPassword({email,password:p});if(error)throw error;if(!await isAdmin(data.session.user.id))throw new Error('این حساب مدیر نیست.');localStorage.removeItem(store);await showDashboard(data.session)}catch(err){console.error(err);g.fails=(g.fails||0)+1;if(g.fails>=5){g={fails:0,blockedUntil:Date.now()+10*60*1000}}localStorage.setItem(store,JSON.stringify(g));K.setMessage(loginMessage,g.blockedUntil>Date.now()?'ورود به‌دلیل تلاش‌های ناموفق برای ۱۰ دقیقه محدود شد.':(String(err.message).includes('Invalid')?'نام کاربری یا رمز مدیر صحیح نیست.':err.message),'error');b.disabled=false}});
  el('settings-form').addEventListener('submit',async e=>{e.preventDefault();const b=e.currentTarget.querySelector('button'),m=el('settings-message');b.disabled=true;const r=await K.client.rpc('gol_admin_update_settings',{p_registration_open:el('registration-open').checked,p_registration_deadline:new Date(el('deadline-input').value).toISOString(),p_deadline_label:el('deadline-label').value.trim(),p_min_age:Number(el('minimum-age').value),p_fee_toman:Number(el('fee-input').value),p_bank_account:el('bank-account').value.trim(),p_account_holder:el('account-holder').value.trim()});K.setMessage(m,r.error?'ذخیره تنظیمات انجام نشد.':'تنظیمات ذخیره شد.',r.error?'error':'success');b.disabled=false;if(!r.error)await loadSettings()});
  el('refresh-button').addEventListener('click',loadAll);el('export-button').addEventListener('click',()=>{const rows=[['نام تیم','تلفن کاپیتان','وضعیت','ثبت ناقص','تعداد تعویض','تغییرات در انتظار بررسی','نام بازیکن','نقش','نام پدر','کد ملی','تولد','فیش','تاریخ ثبت']];teams.forEach(t=>{const ps=t.gol_players||[];if(!ps.length)rows.push([t.team_name,t.captain_phone,K.statusLabels[t.status]||t.status,'بله',t.replacement_count||0,t.changes_pending_review?'بله':'خیر','','','','','',t.payment_receipt_path?'دارد':'ندارد',t.created_at]);ps.forEach(p=>rows.push([t.team_name,t.captain_phone,K.statusLabels[t.status]||t.status,(t.status==='incomplete'||ps.length<5)?'بله':'خیر',t.replacement_count||0,t.changes_pending_review?'بله':'خیر',p.full_name,p.is_captain?'کاپیتان':'بازیکن',p.father_name,p.national_id,`${p.birth_year}/${p.birth_month}/${p.birth_day}`,t.payment_receipt_path?'دارد':'ندارد',t.created_at]))});const csv='\uFEFF'+rows.map(r=>r.map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(',')).join('\n'),url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='gol-koochik-full-backup.csv';a.click();URL.revokeObjectURL(url)});logoutButton.addEventListener('click',async()=>{await K.client.auth.signOut();location.reload()});
  const session=await K.currentSession();if(session)try{await showDashboard(session)}catch(e){console.error(e);K.setMessage(loginMessage,e.message,'error')}
})();